# Config file for automatic testing at travis-ci.com

language: python
dist: xenial

branches:
  only:
  - master
  - develop

matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: '3.7'
      env:
        - TOXENV=docs
    - python: '3.7'
      env:
        - TOXENV=linter
    - python: '3.8'
      env:
        - TOXENV=py38

install:
  - pip install tox

addons:
    apt:
        packages:
            - graphviz

script:
  - tox

